
env:
  CIRRUS_CLONE_DEPTH: 1
  CIRRUS_CLONE_SUBMODULES: true

task:
    name: FreeBSD
    freebsd_instance:
        matrix:
            image_family: freebsd-14-3
            image_family: freebsd-13-5

    install_script: pwd && ls -la && pkg update --force && pkg install -y cmake glib alsa-lib ladspa portaudio pulseaudio pkgconf sdl2
    
    compile_script: pwd && ls -la && mkdir $HOME/fluidsynth_install/ && mkdir build && cd build && cmake -Werror=dev -DCMAKE_INSTALL_PREFIX=$HOME/fluidsynth_install -Denable-portaudio=1 -Denable-ladspa=1 -Denable-limiter=0 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_VERBOSE_MAKEFILE=0  -DNO_GUI=1 .. && make -j4 && make check && make install

