
resources:
  containers:
  - container: alpine-linux
    endpoint: 'myDockerHub'
    image: alpine:3.17.3

jobs:
  - job: Alpine
    pool:
      vmImage: 'ubuntu-latest'
    container: alpine-linux
    steps:
    - checkout: self
    - bash: |
        apk add alpine-sdk cmake
      displayName: 'Install prerequ'
    - task: CMake@1
      displayName: 'CMake configure'
      inputs:
        cmakeArgs: ..
        workingDirectory: 'build'
    - task: CMake@1
      displayName: 'CMake Build'
      inputs:
        cmakeArgs: --build . --parallel
        workingDirectory: 'build'
    - task: CMake@1
      displayName: 'CMake Check'
      inputs:
        cmakeArgs: --build . --target check --parallel
        workingDirectory: 'build'
