
# NOTE: This Azure Pipeline has been migrated to GitHub Actions (.github/workflows/windows.yml)
# All Windows build jobs have been moved to GitHub Actions for better integration
# with GitHub releases and website announcements.
#
# The following jobs were migrated:
# - Windows10 (x86/x64 MSVC builds) -> msvc-build job in GitHub Actions
# - Windows10Additional (various MSVC configurations) -> msvc-additional job in GitHub Actions  
# - WindowsMinGW (MinGW builds) -> mingw-build job in GitHub Actions
#
# This file is kept for reference but should no longer be actively used.

trigger: none # Disable triggers since builds moved to GitHub Actions

variables:
    # These variables are now defined in GitHub Actions as repository variables
    # and should be configured there by maintainers:
    # - GTK_BUNDLE_X86
    # - GTK_BUNDLE_X64  
    # - LIBSNDFILE_URL_X86
    # - LIBSNDFILE_URL_X64
    # - MINGW_URL_X64
    sdl3-url: 'https://github.com/libsdl-org/SDL/releases/download/release-3.2.10/SDL3-devel-3.2.10-VC.zip'
      
# All jobs removed - builds now happen in GitHub Actions
jobs: []
