ARG BASE_IMAGE=alpine:3.18
FROM ${BASE_IMAGE}

RUN apk add --no-cache --virtual .pipeline-deps readline linux-pam \
  && apk add bash sudo shadow \
  && apk add \
    cmake make \
    glib-dev \
    ladspa-dev \
    nodejs-current \
    gcc g++ \
    pkgconf \
  && apk del .pipeline-deps

LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/bin/node"

CMD [ "node" ]
