FROM node:14-alpine

RUN apk add --no-cache --virtual .pipeline-deps readline linux-pam \
  && apk add bash sudo shadow \
  && apk add alsa-lib-dev \
    cmake \
    dbus-dev \
    glib-dev \
    jack-dev \
    ladspa-dev \
    libsndfile-dev \
    pipewire-dev \
    portaudio-dev \
    pulseaudio-dev \
    readline-dev \
    gcc g++ libgomp \
    pkgconf \
  && apk del .pipeline-deps

LABEL "com.azure.dev.pipelines.agent.handler.node.path"="/usr/local/bin/node"

CMD [ "node" ]
