name: 💡 Feature Request
description: Suggest a concrete feature for FluidSynth
labels: [enhancement]
type: "Feature"

body:
  - type: markdown
    attributes:
      value: |
        **DO NOT SUBMIT SUPPORT REQUESTS OR "HOW TO" QUESTIONS HERE!**
        Else it might be closed without further notice.

        Please fill out the following form to help us understand your feature request.

  - type: input
    id: related-discussion
    attributes:
      label: Related discussion
      description: |
        Feature requests should be discussed by the community, either on the mailing
        list or via a GitHub Discussion. Please bring up your ideas there before
        opening tickets. In case you already did that, please provide a link to the thread.
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: |
        A clear and concise description of what the problem is.
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: |
        Any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
