name: Deploy FluidSynth wiki

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["master"]

    workflow_dispatch:

permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v6

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install zensical
              run: pip install zensical

            - name: Build
              run: zensical build --clean

            - name: Setup Pages
              uses: actions/configure-pages@v5

            - name: Upload artifact
              uses: actions/upload-pages-artifact@v4
              with:
                  name: fluidsynth-wiki
                  # Upload site folder
                  path: "./site"
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
