name: FluidSynth FreeBSD

on:
  pull_request:
  push:
    branches:
      - '**'
    paths-ignore:
      - '.azure/**'
      - '.circleci/**'
      - '.github/workflows/api_doc_build.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/ios.yml'
      - '.github/workflows/os2.yml'
      - '.github/workflows/rendering-regression.yml'
      - '.github/workflows/sonarcloud.yml'
      - '.github/workflows/solaris.yml'
      - '.github/workflows/windows.yml'
      - 'README.md'

env:
  BUILD_TYPE: RelWithDebInfo

defaults:
  run:
    shell: bash

jobs:
    freebsd:
        name: FreeBSD
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            include:
              - release: "15"
                arch: "x86_64"
              - release: "14"
                arch: "x86_64"
              - release: "13"
                arch: "x86_64"
        steps:
        - name: Checkout
          uses: actions/checkout@v7
          with:
            submodules: true

        - name: Build & test
          uses: vmactions/freebsd-vm@v1
          with:
            release: ${{ matrix.release }}
            arch: ${{ matrix.arch }}
            prepare: |
                pkg install -y \
                  cmake \
                  pkgconf \
                  git \
                  ninja \
                  gcem \
                  libsndfile \
                  readline

            run: |
                set -ex
                cmake -S . -G Ninja \
                  -B build \
                  -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
                  -DCMAKE_VERBOSE_MAKEFILE=1 \
                  -Denable-readline=1 \
                  -Denable-libsndfile=1 \
                  -Werror=dev
                cmake --build build
                cmake --build build --target check
                cmake --build build --target demo

