name: FluidSynth MacOSX

on:
  pull_request:
  push:
    paths-ignore:
      - '.azure/**'
      - '.circleci/**'
      - '.github/workflows/sonarcloud.yml'
      - '.github/workflows/linux.yml'
      - '.cirrus.yml'
      - 'README.md'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo
jobs:
  build:
    runs-on: 'macos-11'
    steps:
      - uses: actions/checkout@v2

      - name: 'Install Dependencies'
        run: |
          PACKAGES="glib gobject-introspection libsndfile pkg-config jack dbus-glib pulseaudio portaudio sdl2"
          brew install $PACKAGES

      - name: 'Configure fluidsynth'
        run: |
          export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Werror=dev -DCMAKE_INSTALL_PREFIX=$(Build.ArtifactStagingDirectory) -DCMAKE_VERBOSE_MAKEFILE=1 -DNO_GUI=1
          
      - name: 'Compile fluidsynth'
        # Build your program with the given configuration
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: 'Execute Unittests'
        working-directory: ${{github.workspace}}/build
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target check
